language: generic
sudo: required
services:
    - docker

berfore_install:
    - docker build -t federicoklappenbach/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true federicoklappenbach/docker-react npm run test -- --coverage